package com.softhinkers.selenium.test;
// Generated by Selenium IDE

import com.softhinkers.selenium.page.LoginPage;
import com.softhinkers.selenium.page.HomePage;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.PageFactory;

import java.util.*;

public class LoginTest {
    LoginPage loginPage;
    HomePage homePage;
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private final String baseUrl = "http://www.softhinkers.com/";
    private final String inputPasswordId = "inputPassword";

    @Before
    public void setUp() {

        System.setProperty("webdriver.chrome.driver", "C:/Users/SWATI/Downloads/chromedriver_win32/chromedriver.exe");
        driver = new ChromeDriver();
        driver.get(baseUrl);
        loginPage = PageFactory.initElements(driver, LoginPage.class);
        homePage = PageFactory.initElements(driver, HomePage.class);


        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.close();
        driver.quit();
    }

    @Test
    public void login() {
        homePage.clickOnLoginButton();
        loginPage.inputUsername("softhinkers");
        loginPage.inputPassword("xxx");
        loginPage.clickOnSubmitButton();
    }
}
